name: 
on:
  schedule:
    # 每天0:00执行
    - cron: "0 0 * * *"
    # 每天12:00执行
    - cron: "0 12 * * *"
  workflow_dispatch:

concurrency:
  group: {{}}
  cancel-in-progress: true

env:
  # time zone
  TZ: 

  # github access token
  GIST_PAT: {{}}

  # github username and gist id, separated by '/'
  GIST_LINK: {{}}

  # the url to the list of airports that you maintain yourself
  # each line include domain, coupon and invitation code, the domain must be included, and the latter two items are optional
  CUSTOMIZE_LINK: {{}}

  # include special protocols, such as vless hysteria2 and hysteria
  ENABLE_SPECIAL_PROTOCOLS: {{}}

jobs:
  process:
    runs-on: 

    steps:
      - name: 
        uses: 
        with:
          ref: 

      - name: 
        uses: 
        with:
          python-version: "3.x"
          architecture: "x64"
          cache: "pip"

      - name: 
        run: 

      - name: 
        run: |
          if [ -z "$GIST_PAT" ]; then
              echo "Error: environment 'GIST_PAT' cannot be empty"
              exit 1
          fi

          if [ -z "$GIST_LINK" ]; then
              echo "Error: environment 'GIST_LINK' cannot be empty"
              exit 1
          fi

          LINK_PARTS=$(echo "$GIST_LINK" | awk -F'/' 'NF==2 && $1!="" && $2!=""')
          if [ -z "$LINK_PARTS" ]; then
              echo "Error: environment 'GIST_LINK' is not valid, should be 'username/gist_id' format"
              exit 1
          fi

      - name: Collect
        run: python -u subscribe/collect.py --all --overwrite --skip

      - name: Timestamp
        run: date
